// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lovwfoeuigdkejsmzvvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxvdndmb2V1aWdka2Vqc216dnZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMzczNzUsImV4cCI6MjA2MTgxMzM3NX0.3OAF6AqC7H5jdl3ZELUJTsWc_haVPVIUaXB8JIZvLEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);